name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build it
        run:  docker build . -f .github/Dockerfile.CI -t openarena_test
